// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHUwHqeL_yahNLT8ku2ewvrYddF43ExcY',
    appId: '1:279866766379:web:2a1c0a5c92f2c4d912266e',
    messagingSenderId: '279866766379',
    projectId: 'store-app-1c24c',
    authDomain: 'store-app-1c24c.firebaseapp.com',
    storageBucket: 'store-app-1c24c.appspot.com',
    measurementId: 'G-TXJ74N59LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD--xYFwnfmA1NGI1bYBdj36uou7zriKYQ',
    appId: '1:279866766379:android:c87aeef69a917ada12266e',
    messagingSenderId: '279866766379',
    projectId: 'store-app-1c24c',
    storageBucket: 'store-app-1c24c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsGWbUSG96OPUzUEevIdYM4Z4mDgdKQxE',
    appId: '1:279866766379:ios:8efd40c2c993023e12266e',
    messagingSenderId: '279866766379',
    projectId: 'store-app-1c24c',
    storageBucket: 'store-app-1c24c.appspot.com',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsGWbUSG96OPUzUEevIdYM4Z4mDgdKQxE',
    appId: '1:279866766379:ios:67b24179ca86aa4b12266e',
    messagingSenderId: '279866766379',
    projectId: 'store-app-1c24c',
    storageBucket: 'store-app-1c24c.appspot.com',
    iosBundleId: 'com.example.storeApp.RunnerTests',
  );
}
